import { createMockUser } from '@/lib/mock-utils';
import type { Role, User } from '@/types/auth';
import type { Department } from '@/types/department';
import type { UserSelectionResponse } from '@/types/user';

import type { AssignedProjectItem, Project, UnassignedProjectItem } from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    receive_no: 'RCV-2024-001',
    title: 'จัดซื้อเครื่องคอมพิวเตอร์สำนักงาน 10 เครื่อง',
    budget: 250000,
    pr_no: 'PR-67001',
    po_no: null,
    status: 'UNASSIGNED',
    workflow_status: { p: 'NOT_STARTED', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-IT-HARDWARE',
    current_step_id: 'STEP-INIT',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'IT City Co., Ltd.',
    vendor_tax_id: '0105551234567',
    vendor_email: 'sales@itcity.co.th',
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-10T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-10T09:00:00Z').toISOString(),
  },
  {
    id: '2',
    receive_no: 'RCV-2024-002',
    title: 'จ้างเหมาทำความสะอาดอาคารเรียนรวม',
    budget: 1200000,
    pr_no: 'PR-67002',
    po_no: 'PO-67001',
    status: 'WAITING_ACCEPT',
    workflow_status: { p: 'NOT_STARTED', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-SERVICE-CLEANING',
    current_step_id: 'STEP-TOR-REVIEW',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-11T10:30:00Z').toISOString(),
    updated_at: new Date('2024-01-12T08:15:00Z').toISOString(),
  },
  {
    id: '3',
    receive_no: 'RCV-2024-003',
    title: 'จัดซื้อวัสดุสำนักงานประจำไตรมาสที่ 1',
    budget: 45000,
    pr_no: 'PR-67003',
    po_no: 'PO-67002',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-ADMIN',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-SIGN-CONTRACT',
    assignee_procurement: [
      createMockUser(
        'u-101',
        'procure01',
        'นายสมชาย ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-109',
        'contract02',
        'นายปัญญา รอบรู้',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: 'CN-67001',
    migo_no: null,
    vendor_name: 'Office Mate',
    vendor_tax_id: '0105558889991',
    vendor_email: 'contact@officemate.co.th',
    urgent_status: 'URGENT',
    created_by: 'user-06',
    created_at: new Date('2024-01-12T13:00:00Z').toISOString(),
    updated_at: new Date('2024-01-15T09:45:00Z').toISOString(),
  },
  {
    id: '4',
    receive_no: 'RCV-2024-004',
    title: 'ซ่อมแซมระบบปรับอากาศห้องประชุมใหญ่',
    budget: 85000,
    pr_no: 'PR-67004',
    po_no: null,
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-REPAIR',
    current_step_id: 'STEP-SURVEY',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง รักงาน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-108',
        'contract01',
        'นางสาวชูใจ ใฝ่เรียน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Cool Air Service',
    vendor_tax_id: '0105557771112',
    vendor_email: 'service@coolair.com',
    urgent_status: 'URGENT',
    created_by: 'user-01',
    created_at: new Date('2024-01-13T08:00:00Z').toISOString(),
    updated_at: new Date('2024-01-13T08:00:00Z').toISOString(),
  },
  {
    id: '5',
    receive_no: 'RCV-2024-005',
    title: 'โครงการจัดซื้อกล้องวงจรปิด CCTV 20 จุด',
    budget: 550000,
    pr_no: 'PR-67005',
    po_no: 'PO-67003',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'IN_PROGRESS step 4', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-SECURITY',
    current_templates_id: 'TEMPLATE-IT-HARDWARE',
    current_step_id: 'STEP-INSPECT-DELIVERY',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง รักงาน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: 'CN-67002',
    migo_no: 'MIGO-67001',
    vendor_name: 'Secure System Co.',
    vendor_tax_id: '0105553334445',
    vendor_email: 'info@securesys.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-07',
    created_at: new Date('2024-01-05T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-20T11:00:00Z').toISOString(),
  },
  {
    id: '6',
    receive_no: 'RCV-2024-006',
    title: 'จ้างที่ปรึกษาพัฒนาระบบ ERP',
    budget: 4500000,
    pr_no: null,
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'IN_PROGRESS step 2' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-CONSULT',
    current_step_id: 'STEP-TOR-DRAFT',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง รักงาน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-108',
        'contract01',
        'นางสาวชูใจ ใฝ่เรียน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-08',
    created_at: new Date('2024-01-21T14:00:00Z').toISOString(),
    updated_at: new Date('2024-01-21T14:00:00Z').toISOString(),
  },
  {
    id: '7',
    receive_no: 'RCV-2024-007',
    title: 'จัดซื้อครุภัณฑ์โต๊ะเก้าอี้ห้องเรียน 50 ชุด',
    budget: 150000,
    pr_no: 'PR-67006',
    po_no: 'PO-67004',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-EDU',
    current_templates_id: 'TEMPLATE-FURNITURE',
    current_step_id: 'STEP-CLOSE',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง รักงาน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-109',
        'contract02',
        'นายปัญญา รอบรู้',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: 'CN-67003',
    migo_no: 'MIGO-67002',
    vendor_name: 'Furniture World',
    vendor_tax_id: '0105556667778',
    vendor_email: 'sales@furnworld.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-09',
    created_at: new Date('2023-12-15T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-10T15:30:00Z').toISOString(),
  },
  {
    id: '8',
    receive_no: 'RCV-2024-008',
    title: 'ยกเลิก - โครงการจัดนิทรรศการวิทยาศาสตร์',
    budget: 300000,
    pr_no: 'PR-67007',
    po_no: null,
    status: 'CANCELLED',
    workflow_status: { p: 'CANCELLED', c: 'CANCELLED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-SCIENCE',
    current_templates_id: 'TEMPLATE-EVENT',
    current_step_id: 'STEP-CANCEL',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Event Organizer Pro',
    vendor_tax_id: '0105559990001',
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-10',
    created_at: new Date('2024-01-18T09:30:00Z').toISOString(),
    updated_at: new Date('2024-01-19T10:00:00Z').toISOString(),
  },
  {
    id: '9',
    receive_no: 'RCV-2024-009',
    title: 'จัดซื้อน้ำดื่มสำหรับผู้บริหาร',
    budget: 5000,
    pr_no: 'PR-67008',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-ADMIN',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-PRICE-COMPARE',
    assignee_procurement: [
      createMockUser(
        'u-103',
        'procure03',
        'นายวิทยา ฉลาดซื้อ',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Water Co.',
    vendor_tax_id: '0105551112223',
    vendor_email: 'order@waterco.com',
    urgent_status: 'URGENT',
    created_by: 'user-06',
    created_at: new Date('2024-01-22T08:45:00Z').toISOString(),
    updated_at: new Date('2024-01-22T08:45:00Z').toISOString(),
  },
  {
    id: '10',
    receive_no: 'RCV-2024-010',
    title: 'จ้างเหมาบริการรักษาความปลอดภัย ประจำปี 2567',
    budget: 2400000,
    pr_no: 'PR-67009',
    po_no: 'PO-67005',
    status: 'WAITING_ACCEPT',
    workflow_status: { p: 'COMPLETED', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-SECURITY',
    current_templates_id: 'TEMPLATE-SERVICE-SECURITY',
    current_step_id: 'STEP-MONTHLY-INSPECT',
    assignee_procurement: [
      createMockUser(
        'u-104',
        'procure04',
        'นางสาวสมปอง ปลอดภัย',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: 'CN-67004',
    migo_no: 'MIGO-67003',
    vendor_name: 'G4S Security',
    vendor_tax_id: '0105554445556',
    vendor_email: 'contact@g4s.co.th',
    urgent_status: 'NORMAL',
    created_by: 'user-07',
    created_at: new Date('2023-11-20T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-23T11:00:00Z').toISOString(),
  },
  {
    id: '11',
    receive_no: 'RCV-2024-011',
    title: 'จัดซื้อ Software License Microsoft Office',
    budget: 800000,
    pr_no: 'PR-67010',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'WAITING_APPROVAL step 1', c: 'NOT_STARTED' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-SOFTWARE',
    current_step_id: 'STEP-VENDOR-SELECTION',
    assignee_procurement: [
      createMockUser(
        'u-101',
        'procure01',
        'นายสมชาย ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Soft Solutions',
    vendor_tax_id: '0105552223334',
    vendor_email: 'sales@softsol.com',
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-24T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-25T14:20:00Z').toISOString(),
  },
  {
    id: '12',
    receive_no: 'RCV-2024-012',
    title: 'จัดซื้อรถกระบะ 4 ประตู สำหรับงานภาคสนาม',
    budget: 950000,
    pr_no: 'PR-67011',
    po_no: 'PO-67006',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-FIELD',
    current_templates_id: 'TEMPLATE-VEHICLE',
    current_step_id: 'STEP-GUARANTEE-CHECK',
    assignee_procurement: [
      createMockUser(
        'u-104',
        'procure04',
        'นางสาวสมปอง ปลอดภัย',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: 'CN-67005',
    migo_no: null,
    vendor_name: 'Toyota Dealer',
    vendor_tax_id: '0105557778889',
    vendor_email: 'sales@toyota-dealer.com',
    urgent_status: 'URGENT',
    created_by: 'user-11',
    created_at: new Date('2024-01-08T13:30:00Z').toISOString(),
    updated_at: new Date('2024-01-26T09:15:00Z').toISOString(),
  },
  {
    id: '13',
    receive_no: 'RCV-2024-013',
    title: 'ซ่อมบำรุงลิฟต์โดยสาร อาคาร 3',
    budget: 60000,
    pr_no: 'PR-67012',
    po_no: 'PO-67007',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-MAINTENANCE',
    current_step_id: 'STEP-PAYMENT',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-105',
        'contract05',
        'นายสมชาย สัญญา',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: 'MIGO-67004',
    vendor_name: 'Elevator Expert',
    vendor_tax_id: '0105550001112',
    vendor_email: 'service@elevator.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-01',
    created_at: new Date('2023-12-25T11:00:00Z').toISOString(),
    updated_at: new Date('2024-01-15T16:00:00Z').toISOString(),
  },
  {
    id: '14',
    receive_no: 'RCV-2024-014',
    title: 'จัดซื้อสารเคมีสำหรับห้องปฏิบัติการ',
    budget: 120000,
    pr_no: 'PR-67013',
    po_no: null,
    status: 'REQUEST_EDIT',
    workflow_status: { p: 'COMPLETED', c: 'REQUEST_EDIT' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-LAB',
    current_templates_id: 'TEMPLATE-CHEMICAL',
    current_step_id: 'STEP-APPROVE-BUDGET',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Chemical Supply',
    vendor_tax_id: '0105556669990',
    vendor_email: 'sales@chemsupply.com',
    urgent_status: 'NORMAL',
    created_by: 'user-12',
    created_at: new Date('2024-01-27T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-27T09:00:00Z').toISOString(),
  },
  {
    id: '15',
    receive_no: 'RCV-2024-015',
    title: 'จ้างออกแบบสื่อสิ่งพิมพ์ประชาสัมพันธ์หลักสูตร',
    budget: 35000,
    pr_no: 'PR-67014',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'REJECTED step 1', c: 'NOT_STARTED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-PR',
    current_templates_id: 'TEMPLATE-DESIGN',
    current_step_id: 'STEP-DRAFT-REQ',
    assignee_procurement: [
      createMockUser(
        'u-103',
        'procure03',
        'นายวิทยา ฉลาดซื้อ',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Freelance Design',
    vendor_tax_id: '1100555123456',
    vendor_email: 'art@freelance.com',
    urgent_status: 'NORMAL',
    created_by: 'user-13',
    created_at: new Date('2024-01-28T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-28T10:00:00Z').toISOString(),
  },
  {
    id: '16',
    receive_no: 'RCV-2024-016',
    title: 'โครงการอบรมพัฒนาบุคลากรด้านภาษาอังกฤษ',
    budget: 180000,
    pr_no: 'PR-67015',
    po_no: 'PO-67008',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-HR',
    current_templates_id: 'TEMPLATE-TRAINING',
    current_step_id: 'STEP-EVALUATE',
    assignee_procurement: [
      createMockUser(
        'u-103',
        'procure03',
        'นายวิทยา ฉลาดซื้อ',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [],
    contract_no: 'CN-67006',
    migo_no: null,
    vendor_name: 'Language Center',
    vendor_tax_id: '0105558882221',
    vendor_email: 'train@langcenter.com',
    urgent_status: 'NORMAL',
    created_by: 'user-14',
    created_at: new Date('2024-01-10T14:00:00Z').toISOString(),
    updated_at: new Date('2024-01-25T13:00:00Z').toISOString(),
  },
  {
    id: '17',
    receive_no: 'RCV-2024-017',
    title: 'จัดซื้อเครื่องปั่นเหวี่ยงตกตะกอน (Centrifuge)',
    budget: 350000,
    pr_no: 'PR-67016',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'REJECTED step 1' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-LAB',
    current_templates_id: 'TEMPLATE-LAB-EQUIP',
    current_step_id: 'STEP-ANNOUNCE',
    assignee_procurement: [
      createMockUser(
        'u-101',
        'procure01',
        'นายสมชาย ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-106',
        'contract06',
        'นางสาวสุดา มีความรู้',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-12',
    created_at: new Date('2024-01-20T08:30:00Z').toISOString(),
    updated_at: new Date('2024-01-29T09:00:00Z').toISOString(),
  },
  {
    id: '18',
    receive_no: 'RCV-2024-018',
    title: 'จ้างเหมาเปลี่ยนหลอดไฟ LED ทั้งอาคาร',
    budget: 95000,
    pr_no: 'PR-67017',
    po_no: 'PO-67009',
    status: 'CANCELLED',
    workflow_status: { p: 'COMPLETED', c: 'CANCELLED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-REPAIR',
    current_step_id: 'STEP-CLOSE',
    assignee_procurement: [
      createMockUser(
        'u-102',
        'procure02',
        'นางสาวสมหญิง รักงาน',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-105',
        'contract05',
        'นายสมชาย สัญญา',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: 'MIGO-67005',
    vendor_name: 'Electric Pro',
    vendor_tax_id: '0105553331119',
    vendor_email: 'service@electricpro.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-01',
    created_at: new Date('2023-12-28T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-18T15:00:00Z').toISOString(),
  },
  {
    id: '19',
    receive_no: 'RCV-2024-019',
    title: 'จัดซื้อกระดาษ A4 จำนวน 500 รีม',
    budget: 65000,
    pr_no: 'PR-67018',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'WAITING_APPROVAL step 2' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-STORE',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-STOCK-CHECK',
    assignee_procurement: [
      createMockUser(
        'u-101',
        'procure01',
        'นายสมชาย ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-109',
        'contract02',
        'นายปัญญา รอบรู้',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Paper AA',
    vendor_tax_id: '0105554448882',
    vendor_email: 'sales@paperaa.com',
    urgent_status: 'NORMAL',
    created_by: 'user-06',
    created_at: new Date('2024-01-30T08:00:00Z').toISOString(),
    updated_at: new Date('2024-01-30T08:00:00Z').toISOString(),
  },
  {
    id: '20',
    receive_no: 'RCV-2024-020',
    title: 'จ้างพัฒนา Mobile Application สำหรับนักศึกษา',
    budget: 1500000,
    pr_no: null,
    po_no: null,
    status: 'UNASSIGNED',
    workflow_status: { p: 'COMPLETED', c: 'NOT_STARTED' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-SOFTWARE-DEV',
    current_step_id: 'STEP-TOR-COMMITTEE',
    assignee_procurement: [
      createMockUser(
        'u-101',
        'procure01',
        'นายสมชาย ใจดี',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-01',
        'Procurement Unit'
      ),
    ],
    assignee_contract: [
      createMockUser(
        'u-108',
        'contract02',
        'นางสาวปรียา พัฒนา',
        'GENERAL_STAFF',
        'dept-01',
        'Procurement Department',
        'unit-02',
        'Contract Unit'
      ),
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-15',
    created_at: new Date('2024-01-29T13:00:00Z').toISOString(),
    updated_at: new Date('2024-01-30T09:30:00Z').toISOString(),
  },
];

export const MOCK_ASSIGNED_PROJECTS: AssignedProjectItem[] = [
  {
    id: 'assign_01',
    receive_no: 'RCV-67-001',
    title: 'จัดซื้อเครื่องคอมพิวเตอร์แม่ข่าย',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ฝ่ายเทคโนโลยีสารสนเทศ',
      department: {
        name: 'ฝ่ายเทคโนโลยีสารสนเทศ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'จัดทำใบสั่งซื้อ',
    current_step_order: 2,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-15',
    created_at: '2024-01-10T09:00:00Z',
  },
  {
    id: 'assign_02',
    receive_no: 'RCV-67-002',
    title: 'จ้างเหมาซ่อมแซมระบบไฟฟ้าอาคาร 5',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'กองอาคารสถานที่',
      department: {
        name: 'กองอาคารสถานที่',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-10',
    created_at: '2024-01-11T10:30:00Z',
  },
  {
    id: 'assign_03',
    receive_no: 'RCV-67-003',
    title: 'จัดซื้อกระดาษ A4 และหมึกพิมพ์',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'งานธุรการ',
      department: {
        name: 'งานธุรการ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ตรวจสอบราคา',
    current_step_order: 3,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-20',
    created_at: '2024-01-12T08:15:00Z',
  },
  {
    id: 'assign_04',
    receive_no: 'RCV-67-004',
    title: 'จัดซื้อสารเคมีเพื่อการวิจัย',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'คณะวิทยาศาสตร์',
      department: {
        name: 'คณะวิทยาศาสตร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-103',
    assignee_full_name: 'นายวิชัย เก่งวิทย์',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-01',
    created_at: '2024-01-12T13:00:00Z',
  },
  {
    id: 'assign_05',
    receive_no: 'RCV-67-005',
    title: 'จ้างซ่อมบำรุงรถตู้ ฮฮ-1234',
    status: 'CANCELLED',
    request_unit: {
      name: 'กองยานพาหนะ',
      department: {
        name: 'กองยานพาหนะ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ยกเลิก',
    current_step_order: 0,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'NORMAL',
    expected_approval_date: null,
    created_at: '2024-01-13T09:00:00Z',
  },
  {
    id: 'assign_06',
    receive_no: 'RCV-67-006',
    title: 'จ้างออกแบบและผลิตป้ายไวนิล',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ฝ่ายประชาสัมพันธ์',
      department: {
        name: 'ฝ่ายประชาสัมพันธ์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'จัดทำ TOR',
    current_step_order: 1,
    assignee_id: 'u-104',
    assignee_full_name: 'นางมาลี สีสวย',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-25',
    created_at: '2024-01-14T11:00:00Z',
  },
  {
    id: 'assign_07',
    receive_no: 'RCV-67-007',
    title: 'ต่ออายุสมาชิกฐานข้อมูลออนไลน์',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'สำนักวิทยบริการ',
      department: {
        name: 'สำนักวิทยบริการ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'CONTRACT',
    current_step_name: 'จัดทำสัญญา',
    current_step_order: 5,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-10',
    created_at: '2024-01-15T14:20:00Z',
  },
  {
    id: 'assign_08',
    receive_no: 'RCV-67-008',
    title: 'เช่าสถานที่จัดอบรมผู้บริหาร',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'กองบริหารทรัพยากรบุคคล',
      department: {
        name: 'กองบริหารทรัพยากรบุคคล',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-105',
    assignee_full_name: 'นายกล้าหาญ ชาญชัย',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-05',
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'assign_09',
    receive_no: 'RCV-67-009',
    title: 'จัดซื้อ License Microsoft Office 365',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ศูนย์คอมพิวเตอร์',
      department: {
        name: 'ศูนย์คอมพิวเตอร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    current_step_name: 'อนุมัติแล้ว',
    current_step_order: 10,
    assignee_id: 'u-103',
    assignee_full_name: 'นายวิชัย เก่งวิทย์',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-15',
    created_at: '2024-01-17T09:30:00Z',
  },
  {
    id: 'assign_10',
    receive_no: 'RCV-67-010',
    title: 'จัดซื้อตู้เก็บเอกสารเหล็ก',
    status: 'CANCELLED',
    request_unit: {
      name: 'งานพัสดุ',
      department: {
        name: 'งานพัสดุ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ยกเลิก',
    current_step_order: 0,
    assignee_id: 'u-104',
    assignee_full_name: 'นางมาลี สีสวย',
    urgent_status: 'NORMAL',
    expected_approval_date: null,
    created_at: '2024-01-17T15:45:00Z',
  },
  {
    id: 'assign_11',
    receive_no: 'RCV-67-011',
    title: 'จ้างเหมาทำความสะอาดพรมสำนักงาน',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'ฝ่ายการเงิน',
      department: {
        name: 'ฝ่ายการเงิน',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-28',
    created_at: '2024-01-18T08:30:00Z',
  },
];

export const MOCK_UNASSIGNED_PROJECTS: UnassignedProjectItem[] = [
  {
    id: 'unassign_01',
    receive_no: 'RCV-67-012',
    title: 'จัดซื้อวิทยุสื่อสาร Walkie Talkie',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายรักษาความปลอดภัย',
      department: {
        name: 'ฝ่ายรักษาความปลอดภัย',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-01',
    created_at: '2024-01-19T09:00:00Z',
  },
  {
    id: 'unassign_02',
    receive_no: 'RCV-67-013',
    title: 'จ้างที่ปรึกษาควบคุมงานก่อสร้าง',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'คณะวิศวกรรมศาสตร์',
      department: {
        name: 'คณะวิศวกรรมศาสตร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-28',
    created_at: '2024-01-19T10:30:00Z',
  },
  {
    id: 'unassign_03',
    receive_no: 'RCV-67-014',
    title: 'จัดซื้ออุปกรณ์กีฬาสำหรับโรงยิม',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'กองกิจการนักศึกษา',
      department: {
        name: 'กองกิจการนักศึกษา',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-10',
    created_at: '2024-01-19T13:15:00Z',
  },
  {
    id: 'unassign_04',
    receive_no: 'RCV-67-015',
    title: 'ซ่อมแซมโปรเจคเตอร์ห้องประชุมใหญ่',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายโสตทัศนูปกรณ์',
      department: {
        name: 'ฝ่ายโสตทัศนูปกรณ์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-20',
    created_at: '2024-01-20T08:45:00Z',
  },
  {
    id: 'unassign_05',
    receive_no: 'RCV-67-016',
    title: 'จัดซื้อชุดรับแขกโซฟาหนังแท้',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'สำนักงานผู้อำนวยการ',
      department: {
        name: 'สำนักงานผู้อำนวยการ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-05',
    created_at: '2024-01-20T11:00:00Z',
  },
  {
    id: 'unassign_06',
    receive_no: 'RCV-67-017',
    title: 'จัดซื้อเวชภัณฑ์และอุปกรณ์ปฐมพยาบาล',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'งานอนามัยและพยาบาล',
      department: {
        name: 'งานอนามัยและพยาบาล',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-15',
    created_at: '2024-01-20T14:30:00Z',
  },
  {
    id: 'unassign_07',
    receive_no: 'RCV-67-018',
    title: 'จ้างเหมาดูแลสวนหย่อมและตัดแต่งต้นไม้',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายภูมิสถาปัตย์',
      department: {
        name: 'ฝ่ายภูมิสถาปัตย์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-20',
    created_at: '2024-01-21T09:15:00Z',
  },
  {
    id: 'unassign_08',
    receive_no: 'RCV-67-019',
    title: 'ซื้อวัตถุดิบประกอบอาหารแห้งประจำเดือน',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'แผนกอาหารและเครื่องดื่ม',
      department: {
        name: 'แผนกอาหารและเครื่องดื่ม',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-25',
    created_at: '2024-01-21T10:00:00Z',
  },
  {
    id: 'unassign_09',
    receive_no: 'RCV-67-020',
    title: 'จ้างผู้ตรวจประเมินคุณภาพ ISO 9001',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'งานประกันคุณภาพ',
      department: {
        name: 'งานประกันคุณภาพ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-15',
    created_at: '2024-01-21T15:30:00Z',
  },
  {
    id: 'unassign_10',
    receive_no: 'RCV-67-021',
    title: 'จัดซื้อหูฟังสำหรับการสอบ Listening',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ศูนย์ภาษา',
      department: {
        name: 'ศูนย์ภาษา',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-08',
    created_at: '2024-01-22T08:00:00Z',
  },
];

export const MOCK_USER_SELECTION: UserSelectionResponse = {
  id: 'unit_procure_01',
  name: 'ฝ่ายพัสดุและจัดซื้อ',
  entity_type: 'unit',
  data: [
    {
      id: 'u-101',
      full_name: 'นายสมชาย ใจดี',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-102',
      full_name: 'นางสาวสมหญิง รักงาน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-103',
      full_name: 'นายวิชัย เก่งวิทย์',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-104',
      full_name: 'นางมาลี สีสวย',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-105',
      full_name: 'นายกล้าหาญ ชาญชัย',
      role: 'HEAD_OF_UNIT',
    },
    {
      id: 'u-106',
      full_name: 'นางสาวปิติ ยินดี',
      role: 'DOCUMENT_STAFF',
    },
    {
      id: 'u-107',
      full_name: 'นายมานะ อดทน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-108',
      full_name: 'นางสาวชูใจ ใฝ่เรียน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-109',
      full_name: 'นายปัญญา รอบรู้',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-110',
      full_name: 'นางแก้วตา ดวงใจ',
      role: 'GENERAL_STAFF',
    },
  ],
};

export const MOCK_USER: User = {
  id: 'user-01',
  username: 'user',
  full_name: 'General Staff User',
  is_delegated: false,
  roles: {
    own: [
      {
        role: 'GENERAL_STAFF',
        dept_id: 'dept-01',
        dept_name: 'procurement',
        unit_id: 'unit-01',
        unit_name: 'procurement-1',
      },
    ],
    delegated: [],
  },
};

export const MOCK_USERS_BY_ROLE: Record<string, User> = {
  SUPER_ADMIN: {
    id: 'user-super-admin',
    username: 'superadmin',
    full_name: 'Super Admin User',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'SUPER_ADMIN',
          dept_id: 'dept-01',
          dept_name: 'Administration',
          unit_id: 'unit-01',
          unit_name: 'Executive Office',
        },
      ],
      delegated: [],
    },
  },
  ADMIN: {
    id: 'user-admin',
    username: 'admin',
    full_name: 'Admin User',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'ADMIN',
          dept_id: 'dept-01',
          dept_name: 'Administration',
          unit_id: 'unit-02',
          unit_name: 'Admin Office',
        },
      ],
      delegated: [],
    },
  },
  HEAD_OF_DEPARTMENT: {
    id: 'user-hod',
    username: 'hod',
    full_name: 'Head of Department',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'HEAD_OF_DEPARTMENT',
          dept_id: 'dept-02',
          dept_name: 'Procurement Department',
          unit_id: null,
          unit_name: null,
        },
      ],
      delegated: [],
    },
  },
  HEAD_OF_UNIT: {
    id: 'user-hou',
    username: 'hou',
    full_name: 'Head of Unit',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'HEAD_OF_UNIT',
          dept_id: 'dept-02',
          dept_name: 'Procurement Department',
          unit_id: 'unit-03',
          unit_name: 'Procurement Unit 1',
        },
      ],
      delegated: [],
    },
  },
  REPRESENTATIVE: {
    id: 'user-rep',
    username: 'representative',
    full_name: 'Representative User',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'REPRESENTATIVE',
          dept_id: 'dept-03',
          dept_name: 'Academic Department',
          unit_id: 'unit-04',
          unit_name: 'Academic Unit 1',
        },
      ],
      delegated: [],
    },
  },
  DOCUMENT_STAFF: {
    id: 'user-doc',
    username: 'docstaff',
    full_name: 'Document Staff',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'DOCUMENT_STAFF',
          dept_id: 'dept-01',
          dept_name: 'Procurement Department',
          unit_id: 'unit-05',
          unit_name: 'Document Processing',
        },
      ],
      delegated: [],
    },
  },
  FINANCE_STAFF: {
    id: 'user-finance',
    username: 'financestaff',
    full_name: 'Finance Staff',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'FINANCE_STAFF',
          dept_id: 'dept-04',
          dept_name: 'Finance Department',
          unit_id: 'unit-06',
          unit_name: 'Finance Unit',
        },
      ],
      delegated: [],
    },
  },
  GENERAL_STAFF: {
    id: 'user-general',
    username: 'generalstaff',
    full_name: 'General Staff',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'GENERAL_STAFF',
          dept_id: 'dept-01',
          dept_name: 'Procurement Department',
          unit_id: 'unit-07',
          unit_name: 'General Services',
        },
      ],
      delegated: [],
    },
  },
  GUEST: {
    id: 'user-guest',
    username: 'guest',
    full_name: 'Guest User',
    is_delegated: false,
    roles: {
      own: [
        {
          role: 'GUEST',
          dept_id: null,
          dept_name: null,
          unit_id: null,
          unit_name: null,
        },
      ],
      delegated: [],
    },
  },
};

export const MOCK_USER_PROJECT_STATS = {
  data: [
    {
      id: 'u-101',
      full_name: 'นายสมชาย ใจดี',
      project_count: 12,
    },
    {
      id: 'u-102',
      full_name: 'นางสาวสมหญิง รักงาน',
      project_count: 8,
    },
    {
      id: 'u-103',
      full_name: 'นายวิชัย เก่งวิทย์',
      project_count: 15,
    },
    {
      id: 'u-104',
      full_name: 'นางมาลี สีสวย',
      project_count: 6,
    },
    {
      id: 'u-105',
      full_name: 'นายกล้าหาญ ชาญชัย',
      project_count: 10,
    },
    {
      id: 'u-106',
      full_name: 'นางสาวปิติ ยินดี',
      project_count: 4,
    },
    {
      id: 'u-107',
      full_name: 'นายมานะ อดทน',
      project_count: 9,
    },
    {
      id: 'u-108',
      full_name: 'นางสาวชูใจ ใฝ่เรียน',
      project_count: 7,
    },
    {
      id: 'u-109',
      full_name: 'นายปัญญา รอบรู้',
      project_count: 11,
    },
    {
      id: 'u-110',
      full_name: 'นางแก้วตา ดวงใจ',
      project_count: 5,
    },
    {
      id: 'u-111',
      full_name: 'นายธนา มั่นคง',
      project_count: 13,
    },
    {
      id: 'u-112',
      full_name: 'นางสาวสุดา เพียร',
      project_count: 8,
    },
    {
      id: 'u-113',
      full_name: 'นายประสิทธิ์ ขยัน',
      project_count: 14,
    },
    {
      id: 'u-114',
      full_name: 'นางจิตรา สุขใจ',
      project_count: 6,
    },
    {
      id: 'u-115',
      full_name: 'นายอนุชา รุ่งเรือง',
      project_count: 10,
    },
  ],
};

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'dept-01',
    name: 'คณะวิทยาศาสตร์',
    code: '1001',
  },
  {
    id: 'dept-02',
    name: 'คณะวิศวกรรมศาสตร์',
    code: '1002',
  },
  {
    id: 'dept-03',
    name: 'สำนักวิทยบริการ',
    code: '2001',
  },
  {
    id: 'dept-04',
    name: 'กองบริหารงานบุคคล',
    code: '3001',
  },
  {
    id: 'dept-05',
    name: 'กองอาคารสถานที่',
    code: '3002',
  },
];
