import type { User } from '@/types/auth';
import type { Department } from '@/types/department';
import {
  type AssignedProjectItem,
  type Project,
  type UnassignedProjectItem,
} from '@/types/project';
import { type ProjectDetail } from '@/types/project-detail';
import { type UserSelectionResponse } from '@/types/user';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    receive_no: 'RCV-2024-001',
    title: 'จัดซื้อเครื่องคอมพิวเตอร์สำนักงาน 10 เครื่อง',
    budget: 250000,
    pr_no: 'PR-67001',
    po_no: null,
    status: 'UNASSIGNED',
    workflow_status: { p: 'NOT_STARTED', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-IT-HARDWARE',
    current_step_id: 'STEP-INIT',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'IT City Co., Ltd.',
    vendor_tax_id: '0105551234567',
    vendor_email: 'sales@itcity.co.th',
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-10T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-10T09:00:00Z').toISOString(),
  },
  {
    id: '2',
    receive_no: 'RCV-2024-002',
    title: 'จ้างเหมาทำความสะอาดอาคารเรียนรวม',
    budget: 1200000,
    pr_no: 'PR-67002',
    po_no: 'PO-67001',
    status: 'WAITING_ACCEPT',
    workflow_status: { p: 'NOT_STARTED', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-SERVICE-CLEANING',
    current_step_id: 'STEP-TOR-REVIEW',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-11T10:30:00Z').toISOString(),
    updated_at: new Date('2024-01-12T08:15:00Z').toISOString(),
  },
  {
    id: '3',
    receive_no: 'RCV-2024-003',
    title: 'จัดซื้อวัสดุสำนักงานประจำไตรมาสที่ 1',
    budget: 45000,
    pr_no: 'PR-67003',
    po_no: 'PO-67002',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-ADMIN',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-SIGN-CONTRACT',
    assignee_procurement: [
      {
        id: 'u-101',
        username: 'procure01',
        name: 'นายสมชาย ใจดี',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-1',
      },
    ],
    assignee_contract: [
      {
        id: 'u-109',
        username: 'contract02',
        name: 'นายปัญญา รอบรู้',
        email: 'panya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-9',
      },
    ],
    contract_no: 'CN-67001',
    migo_no: null,
    vendor_name: 'Office Mate',
    vendor_tax_id: '0105558889991',
    vendor_email: 'contact@officemate.co.th',
    urgent_status: 'URGENT',
    created_by: 'user-06',
    created_at: new Date('2024-01-12T13:00:00Z').toISOString(),
    updated_at: new Date('2024-01-15T09:45:00Z').toISOString(),
  },
  {
    id: '4',
    receive_no: 'RCV-2024-004',
    title: 'ซ่อมแซมระบบปรับอากาศห้องประชุมใหญ่',
    budget: 85000,
    pr_no: 'PR-67004',
    po_no: null,
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-REPAIR',
    current_step_id: 'STEP-SURVEY',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง รักงาน',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [
      {
        id: 'u-108',
        username: 'contract01',
        name: 'นางสาวชูใจ ใฝ่เรียน',
        email: 'chujai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-9',
      },
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Cool Air Service',
    vendor_tax_id: '0105557771112',
    vendor_email: 'service@coolair.com',
    urgent_status: 'URGENT',
    created_by: 'user-01',
    created_at: new Date('2024-01-13T08:00:00Z').toISOString(),
    updated_at: new Date('2024-01-13T08:00:00Z').toISOString(),
  },
  {
    id: '5',
    receive_no: 'RCV-2024-005',
    title: 'โครงการจัดซื้อกล้องวงจรปิด CCTV 20 จุด',
    budget: 550000,
    pr_no: 'PR-67005',
    po_no: 'PO-67003',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'IN_PROGRESS step 4', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-SECURITY',
    current_templates_id: 'TEMPLATE-IT-HARDWARE',
    current_step_id: 'STEP-INSPECT-DELIVERY',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง รักงาน',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [],
    contract_no: 'CN-67002',
    migo_no: 'MIGO-67001',
    vendor_name: 'Secure System Co.',
    vendor_tax_id: '0105553334445',
    vendor_email: 'info@securesys.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-07',
    created_at: new Date('2024-01-05T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-20T11:00:00Z').toISOString(),
  },
  {
    id: '6',
    receive_no: 'RCV-2024-006',
    title: 'จ้างที่ปรึกษาพัฒนาระบบ ERP',
    budget: 4500000,
    pr_no: null,
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'IN_PROGRESS step 2' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-CONSULT',
    current_step_id: 'STEP-TOR-DRAFT',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง รักงาน',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [
      {
        id: 'u-108',
        username: 'contract01',
        name: 'นางสาวชูใจ ใฝ่เรียน',
        email: 'panya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-9',
      },
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-08',
    created_at: new Date('2024-01-21T14:00:00Z').toISOString(),
    updated_at: new Date('2024-01-21T14:00:00Z').toISOString(),
  },
  {
    id: '7',
    receive_no: 'RCV-2024-007',
    title: 'จัดซื้อครุภัณฑ์โต๊ะเก้าอี้ห้องเรียน 50 ชุด',
    budget: 150000,
    pr_no: 'PR-67006',
    po_no: 'PO-67004',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-EDU',
    current_templates_id: 'TEMPLATE-FURNITURE',
    current_step_id: 'STEP-CLOSE',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง รักงาน',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [
      {
        id: 'u-109',
        username: 'contract02',
        name: 'นายปัญญา รอบรู้',
        email: 'panya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-9',
      },
    ],
    contract_no: 'CN-67003',
    migo_no: 'MIGO-67002',
    vendor_name: 'Furniture World',
    vendor_tax_id: '0105556667778',
    vendor_email: 'sales@furnworld.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-09',
    created_at: new Date('2023-12-15T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-10T15:30:00Z').toISOString(),
  },
  {
    id: '8',
    receive_no: 'RCV-2024-008',
    title: 'ยกเลิก - โครงการจัดนิทรรศการวิทยาศาสตร์',
    budget: 300000,
    pr_no: 'PR-67007',
    po_no: null,
    status: 'CANCELLED',
    workflow_status: { p: 'CANCELLED', c: 'CANCELLED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-SCIENCE',
    current_templates_id: 'TEMPLATE-EVENT',
    current_step_id: 'STEP-CANCEL',
    assignee_procurement: [],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Event Organizer Pro',
    vendor_tax_id: '0105559990001',
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-10',
    created_at: new Date('2024-01-18T09:30:00Z').toISOString(),
    updated_at: new Date('2024-01-19T10:00:00Z').toISOString(),
  },
  {
    id: '9',
    receive_no: 'RCV-2024-009',
    title: 'จัดซื้อน้ำดื่มสำหรับผู้บริหาร',
    budget: 5000,
    pr_no: 'PR-67008',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-ADMIN',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-PRICE-COMPARE',
    assignee_procurement: [
      {
        id: 'u-103',
        username: 'procure03',
        name: 'นายวิทยา ฉลาดซื้อ',
        email: 'vidya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-3',
      },
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Water Co.',
    vendor_tax_id: '0105551112223',
    vendor_email: 'order@waterco.com',
    urgent_status: 'URGENT',
    created_by: 'user-06',
    created_at: new Date('2024-01-22T08:45:00Z').toISOString(),
    updated_at: new Date('2024-01-22T08:45:00Z').toISOString(),
  },
  {
    id: '10',
    receive_no: 'RCV-2024-010',
    title: 'จ้างเหมาบริการรักษาความปลอดภัย ประจำปี 2567',
    budget: 2400000,
    pr_no: 'PR-67009',
    po_no: 'PO-67005',
    status: 'WAITING_ACCEPT',
    workflow_status: { p: 'COMPLETED', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-SECURITY',
    current_templates_id: 'TEMPLATE-SERVICE-SECURITY',
    current_step_id: 'STEP-MONTHLY-INSPECT',
    assignee_procurement: [
      {
        id: 'u-104',
        username: 'procure04',
        name: 'นางสาวสมปอง ปลอดภัย',
        email: 'sompong@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-4',
      },
    ],
    assignee_contract: [],
    contract_no: 'CN-67004',
    migo_no: 'MIGO-67003',
    vendor_name: 'G4S Security',
    vendor_tax_id: '0105554445556',
    vendor_email: 'contact@g4s.co.th',
    urgent_status: 'NORMAL',
    created_by: 'user-07',
    created_at: new Date('2023-11-20T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-23T11:00:00Z').toISOString(),
  },
  {
    id: '11',
    receive_no: 'RCV-2024-011',
    title: 'จัดซื้อ Software License Microsoft Office',
    budget: 800000,
    pr_no: 'PR-67010',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'WAITING_APPROVAL step 1', c: 'NOT_STARTED' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-SOFTWARE',
    current_step_id: 'STEP-VENDOR-SELECTION',
    assignee_procurement: [
      {
        id: 'u-101',
        username: 'procure01',
        name: 'นายสมชาย ใจดี',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-1',
      },
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Soft Solutions',
    vendor_tax_id: '0105552223334',
    vendor_email: 'sales@softsol.com',
    urgent_status: 'NORMAL',
    created_by: 'user-01',
    created_at: new Date('2024-01-24T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-25T14:20:00Z').toISOString(),
  },
  {
    id: '12',
    receive_no: 'RCV-2024-012',
    title: 'จัดซื้อรถกระบะ 4 ประตู สำหรับงานภาคสนาม',
    budget: 950000,
    pr_no: 'PR-67011',
    po_no: 'PO-67006',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-FIELD',
    current_templates_id: 'TEMPLATE-VEHICLE',
    current_step_id: 'STEP-GUARANTEE-CHECK',
    assignee_procurement: [
      {
        id: 'u-104',
        username: 'procure04',
        name: 'นางสาวสมปอง ปลอดภัย',
        email: 'sompong@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-4',
      },
    ],
    assignee_contract: [],
    contract_no: 'CN-67005',
    migo_no: null,
    vendor_name: 'Toyota Dealer',
    vendor_tax_id: '0105557778889',
    vendor_email: 'sales@toyota-dealer.com',
    urgent_status: 'URGENT',
    created_by: 'user-11',
    created_at: new Date('2024-01-08T13:30:00Z').toISOString(),
    updated_at: new Date('2024-01-26T09:15:00Z').toISOString(),
  },
  {
    id: '13',
    receive_no: 'RCV-2024-013',
    title: 'ซ่อมบำรุงลิฟต์โดยสาร อาคาร 3',
    budget: 60000,
    pr_no: 'PR-67012',
    po_no: 'PO-67007',
    status: 'CLOSED',
    workflow_status: { p: 'COMPLETED', c: 'COMPLETED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-MAINTENANCE',
    current_step_id: 'STEP-PAYMENT',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง ใจดี',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [
      {
        id: 'u-105',
        username: 'contract05',
        name: 'นายสมชาย สัญญา',
        email: 'somchai.contract@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-5',
      },
    ],
    contract_no: null,
    migo_no: 'MIGO-67004',
    vendor_name: 'Elevator Expert',
    vendor_tax_id: '0105550001112',
    vendor_email: 'service@elevator.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-01',
    created_at: new Date('2023-12-25T11:00:00Z').toISOString(),
    updated_at: new Date('2024-01-15T16:00:00Z').toISOString(),
  },
  {
    id: '14',
    receive_no: 'RCV-2024-014',
    title: 'จัดซื้อสารเคมีสำหรับห้องปฏิบัติการ',
    budget: 120000,
    pr_no: 'PR-67013',
    po_no: null,
    status: 'REQUEST_EDIT',
    workflow_status: { p: 'COMPLETED', c: 'REQUEST_EDIT' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-LAB',
    current_templates_id: 'TEMPLATE-CHEMICAL',
    current_step_id: 'STEP-APPROVE-BUDGET',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง ใจดี',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Chemical Supply',
    vendor_tax_id: '0105556669990',
    vendor_email: 'sales@chemsupply.com',
    urgent_status: 'NORMAL',
    created_by: 'user-12',
    created_at: new Date('2024-01-27T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-27T09:00:00Z').toISOString(),
  },
  {
    id: '15',
    receive_no: 'RCV-2024-015',
    title: 'จ้างออกแบบสื่อสิ่งพิมพ์ประชาสัมพันธ์หลักสูตร',
    budget: 35000,
    pr_no: 'PR-67014',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'REJECTED step 1', c: 'NOT_STARTED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-PR',
    current_templates_id: 'TEMPLATE-DESIGN',
    current_step_id: 'STEP-DRAFT-REQ',
    assignee_procurement: [
      {
        id: 'u-103',
        username: 'procure03',
        name: 'นายวิทยา ฉลาดซื้อ',
        email: 'vidya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-3',
      },
    ],
    assignee_contract: [],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Freelance Design',
    vendor_tax_id: '1100555123456',
    vendor_email: 'art@freelance.com',
    urgent_status: 'NORMAL',
    created_by: 'user-13',
    created_at: new Date('2024-01-28T10:00:00Z').toISOString(),
    updated_at: new Date('2024-01-28T10:00:00Z').toISOString(),
  },
  {
    id: '16',
    receive_no: 'RCV-2024-016',
    title: 'โครงการอบรมพัฒนาบุคลากรด้านภาษาอังกฤษ',
    budget: 180000,
    pr_no: 'PR-67015',
    po_no: 'PO-67008',
    status: 'IN_PROGRESS',
    workflow_status: { p: 'PROPOSING step 3', c: 'NOT_STARTED' },
    procurement_type: 'LT500K',
    request_unit_id: 'UNIT-HR',
    current_templates_id: 'TEMPLATE-TRAINING',
    current_step_id: 'STEP-EVALUATE',
    assignee_procurement: [
      {
        id: 'u-103',
        username: 'procure03',
        name: 'นายวิทยา ฉลาดซื้อ',
        email: 'vidya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-3',
      },
    ],
    assignee_contract: [],
    contract_no: 'CN-67006',
    migo_no: null,
    vendor_name: 'Language Center',
    vendor_tax_id: '0105558882221',
    vendor_email: 'train@langcenter.com',
    urgent_status: 'NORMAL',
    created_by: 'user-14',
    created_at: new Date('2024-01-10T14:00:00Z').toISOString(),
    updated_at: new Date('2024-01-25T13:00:00Z').toISOString(),
  },
  {
    id: '17',
    receive_no: 'RCV-2024-017',
    title: 'จัดซื้อเครื่องปั่นเหวี่ยงตกตะกอน (Centrifuge)',
    budget: 350000,
    pr_no: 'PR-67016',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'REJECTED step 1' },
    procurement_type: 'EBIDDING',
    request_unit_id: 'UNIT-LAB',
    current_templates_id: 'TEMPLATE-LAB-EQUIP',
    current_step_id: 'STEP-ANNOUNCE',
    assignee_procurement: [
      {
        id: 'u-101',
        username: 'procure01',
        name: 'นายสมชาย ใจดี',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-1',
      },
    ],
    assignee_contract: [
      {
        id: 'u-106',
        username: 'contract06',
        name: 'นางสาวสุดา มีความรู้',
        email: 'suda@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-6',
      },
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-12',
    created_at: new Date('2024-01-20T08:30:00Z').toISOString(),
    updated_at: new Date('2024-01-29T09:00:00Z').toISOString(),
  },
  {
    id: '18',
    receive_no: 'RCV-2024-018',
    title: 'จ้างเหมาเปลี่ยนหลอดไฟ LED ทั้งอาคาร',
    budget: 95000,
    pr_no: 'PR-67017',
    po_no: 'PO-67009',
    status: 'CANCELLED',
    workflow_status: { p: 'COMPLETED', c: 'CANCELLED' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-FACILITY',
    current_templates_id: 'TEMPLATE-REPAIR',
    current_step_id: 'STEP-CLOSE',
    assignee_procurement: [
      {
        id: 'u-102',
        username: 'procure02',
        name: 'นางสาวสมหญิง รักงาน',
        email: 'somying@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-2',
      },
    ],
    assignee_contract: [
      {
        id: 'u-105',
        username: 'contract05',
        name: 'นายสมชาย สัญญา',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-5',
      },
    ],
    contract_no: null,
    migo_no: 'MIGO-67005',
    vendor_name: 'Electric Pro',
    vendor_tax_id: '0105553331119',
    vendor_email: 'service@electricpro.com',
    urgent_status: 'VERY_URGENT',
    created_by: 'user-01',
    created_at: new Date('2023-12-28T09:00:00Z').toISOString(),
    updated_at: new Date('2024-01-18T15:00:00Z').toISOString(),
  },
  {
    id: '19',
    receive_no: 'RCV-2024-019',
    title: 'จัดซื้อกระดาษ A4 จำนวน 500 รีม',
    budget: 65000,
    pr_no: 'PR-67018',
    po_no: null,
    status: 'IN_PROGRESS',
    workflow_status: { p: 'COMPLETED', c: 'WAITING_APPROVAL step 2' },
    procurement_type: 'LT100K',
    request_unit_id: 'UNIT-STORE',
    current_templates_id: 'TEMPLATE-SUPPLIES',
    current_step_id: 'STEP-STOCK-CHECK',
    assignee_procurement: [
      {
        id: 'u-101',
        username: 'procure01',
        name: 'นายสมชาย ใจดี',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-1',
      },
    ],
    assignee_contract: [
      {
        id: 'u-109',
        username: 'contract02',
        name: 'นายปัญญา รอบรู้',
        email: 'panya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-9',
      },
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: 'Paper AA',
    vendor_tax_id: '0105554448882',
    vendor_email: 'sales@paperaa.com',
    urgent_status: 'NORMAL',
    created_by: 'user-06',
    created_at: new Date('2024-01-30T08:00:00Z').toISOString(),
    updated_at: new Date('2024-01-30T08:00:00Z').toISOString(),
  },
  {
    id: '20',
    receive_no: 'RCV-2024-020',
    title: 'จ้างพัฒนา Mobile Application สำหรับนักศึกษา',
    budget: 1500000,
    pr_no: null,
    po_no: null,
    status: 'UNASSIGNED',
    workflow_status: { p: 'COMPLETED', c: 'NOT_STARTED' },
    procurement_type: 'SELECTION',
    request_unit_id: 'UNIT-IT',
    current_templates_id: 'TEMPLATE-SOFTWARE-DEV',
    current_step_id: 'STEP-TOR-COMMITTEE',
    assignee_procurement: [
      {
        id: 'u-101',
        username: 'procure01',
        name: 'นายสมชาย ใจดี',
        email: 'somchai@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-1',
      },
    ],
    assignee_contract: [
      {
        id: 'u-108',
        username: 'contract02',
        name: 'นางสาวปรียา พัฒนา',
        email: 'priya@gmail.com',
        role: 'GENERAL_STAFF',
        token: 'mock-token-8',
      },
    ],
    contract_no: null,
    migo_no: null,
    vendor_name: null,
    vendor_tax_id: null,
    vendor_email: null,
    urgent_status: 'NORMAL',
    created_by: 'user-15',
    created_at: new Date('2024-01-29T13:00:00Z').toISOString(),
    updated_at: new Date('2024-01-30T09:30:00Z').toISOString(),
  },
];

export const MOCK_ASSIGNED_PROJECTS: AssignedProjectItem[] = [
  {
    id: 'assign_01',
    receive_no: 'RCV-67-001',
    title: 'จัดซื้อเครื่องคอมพิวเตอร์แม่ข่าย',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ฝ่ายเทคโนโลยีสารสนเทศ',
      department: {
        name: 'ฝ่ายเทคโนโลยีสารสนเทศ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'จัดทำใบสั่งซื้อ',
    current_step_order: 2,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-15',
    created_at: '2024-01-10T09:00:00Z',
  },
  {
    id: 'assign_02',
    receive_no: 'RCV-67-002',
    title: 'จ้างเหมาซ่อมแซมระบบไฟฟ้าอาคาร 5',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'กองอาคารสถานที่',
      department: {
        name: 'กองอาคารสถานที่',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-10',
    created_at: '2024-01-11T10:30:00Z',
  },
  {
    id: 'assign_03',
    receive_no: 'RCV-67-003',
    title: 'จัดซื้อกระดาษ A4 และหมึกพิมพ์',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'งานธุรการ',
      department: {
        name: 'งานธุรการ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ตรวจสอบราคา',
    current_step_order: 3,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-20',
    created_at: '2024-01-12T08:15:00Z',
  },
  {
    id: 'assign_04',
    receive_no: 'RCV-67-004',
    title: 'จัดซื้อสารเคมีเพื่อการวิจัย',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'คณะวิทยาศาสตร์',
      department: {
        name: 'คณะวิทยาศาสตร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-103',
    assignee_full_name: 'นายวิชัย เก่งวิทย์',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-01',
    created_at: '2024-01-12T13:00:00Z',
  },
  {
    id: 'assign_05',
    receive_no: 'RCV-67-005',
    title: 'จ้างซ่อมบำรุงรถตู้ ฮฮ-1234',
    status: 'CANCELLED',
    request_unit: {
      name: 'กองยานพาหนะ',
      department: {
        name: 'กองยานพาหนะ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ยกเลิก',
    current_step_order: 0,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'NORMAL',
    expected_approval_date: null,
    created_at: '2024-01-13T09:00:00Z',
  },
  {
    id: 'assign_06',
    receive_no: 'RCV-67-006',
    title: 'จ้างออกแบบและผลิตป้ายไวนิล',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ฝ่ายประชาสัมพันธ์',
      department: {
        name: 'ฝ่ายประชาสัมพันธ์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'จัดทำ TOR',
    current_step_order: 1,
    assignee_id: 'u-104',
    assignee_full_name: 'นางมาลี สีสวย',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-25',
    created_at: '2024-01-14T11:00:00Z',
  },
  {
    id: 'assign_07',
    receive_no: 'RCV-67-007',
    title: 'ต่ออายุสมาชิกฐานข้อมูลออนไลน์',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'สำนักวิทยบริการ',
      department: {
        name: 'สำนักวิทยบริการ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'CONTRACT',
    current_step_name: 'จัดทำสัญญา',
    current_step_order: 5,
    assignee_id: 'u-101',
    assignee_full_name: 'นายสมชาย ใจดี',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-10',
    created_at: '2024-01-15T14:20:00Z',
  },
  {
    id: 'assign_08',
    receive_no: 'RCV-67-008',
    title: 'เช่าสถานที่จัดอบรมผู้บริหาร',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'กองบริหารทรัพยากรบุคคล',
      department: {
        name: 'กองบริหารทรัพยากรบุคคล',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-105',
    assignee_full_name: 'นายกล้าหาญ ชาญชัย',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-05',
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'assign_09',
    receive_no: 'RCV-67-009',
    title: 'จัดซื้อ License Microsoft Office 365',
    status: 'IN_PROGRESS',
    request_unit: {
      name: 'ศูนย์คอมพิวเตอร์',
      department: {
        name: 'ศูนย์คอมพิวเตอร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    current_step_name: 'อนุมัติแล้ว',
    current_step_order: 10,
    assignee_id: 'u-103',
    assignee_full_name: 'นายวิชัย เก่งวิทย์',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-15',
    created_at: '2024-01-17T09:30:00Z',
  },
  {
    id: 'assign_10',
    receive_no: 'RCV-67-010',
    title: 'จัดซื้อตู้เก็บเอกสารเหล็ก',
    status: 'CANCELLED',
    request_unit: {
      name: 'งานพัสดุ',
      department: {
        name: 'งานพัสดุ',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'ยกเลิก',
    current_step_order: 0,
    assignee_id: 'u-104',
    assignee_full_name: 'นางมาลี สีสวย',
    urgent_status: 'NORMAL',
    expected_approval_date: null,
    created_at: '2024-01-17T15:45:00Z',
  },
  {
    id: 'assign_11',
    receive_no: 'RCV-67-011',
    title: 'จ้างเหมาทำความสะอาดพรมสำนักงาน',
    status: 'WAITING_ACCEPT',
    request_unit: {
      name: 'ฝ่ายการเงิน',
      department: {
        name: 'ฝ่ายการเงิน',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    current_step_name: 'รอการตอบรับ',
    current_step_order: 1,
    assignee_id: 'u-102',
    assignee_full_name: 'นางสาวสมหญิง รักงาน',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-28',
    created_at: '2024-01-18T08:30:00Z',
  },
];

export const MOCK_UNASSIGNED_PROJECTS: UnassignedProjectItem[] = [
  {
    id: 'unassign_01',
    receive_no: 'RCV-67-012',
    title: 'จัดซื้อวิทยุสื่อสาร Walkie Talkie',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายรักษาความปลอดภัย',
      department: {
        name: 'ฝ่ายรักษาความปลอดภัย',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-01',
    created_at: '2024-01-19T09:00:00Z',
  },
  {
    id: 'unassign_02',
    receive_no: 'RCV-67-013',
    title: 'จ้างที่ปรึกษาควบคุมงานก่อสร้าง',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'คณะวิศวกรรมศาสตร์',
      department: {
        name: 'คณะวิศวกรรมศาสตร์',
      },
    },
    procurement_type: 'MT500K',
    template_type: 'MT500K',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-28',
    created_at: '2024-01-19T10:30:00Z',
  },
  {
    id: 'unassign_03',
    receive_no: 'RCV-67-014',
    title: 'จัดซื้ออุปกรณ์กีฬาสำหรับโรงยิม',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'กองกิจการนักศึกษา',
      department: {
        name: 'กองกิจการนักศึกษา',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-10',
    created_at: '2024-01-19T13:15:00Z',
  },
  {
    id: 'unassign_04',
    receive_no: 'RCV-67-015',
    title: 'ซ่อมแซมโปรเจคเตอร์ห้องประชุมใหญ่',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายโสตทัศนูปกรณ์',
      department: {
        name: 'ฝ่ายโสตทัศนูปกรณ์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-20',
    created_at: '2024-01-20T08:45:00Z',
  },
  {
    id: 'unassign_05',
    receive_no: 'RCV-67-016',
    title: 'จัดซื้อชุดรับแขกโซฟาหนังแท้',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'สำนักงานผู้อำนวยการ',
      department: {
        name: 'สำนักงานผู้อำนวยการ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-05',
    created_at: '2024-01-20T11:00:00Z',
  },
  {
    id: 'unassign_06',
    receive_no: 'RCV-67-017',
    title: 'จัดซื้อเวชภัณฑ์และอุปกรณ์ปฐมพยาบาล',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'งานอนามัยและพยาบาล',
      department: {
        name: 'งานอนามัยและพยาบาล',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'VERY_URGENT',
    expected_approval_date: '2024-02-15',
    created_at: '2024-01-20T14:30:00Z',
  },
  {
    id: 'unassign_07',
    receive_no: 'RCV-67-018',
    title: 'จ้างเหมาดูแลสวนหย่อมและตัดแต่งต้นไม้',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ฝ่ายภูมิสถาปัตย์',
      department: {
        name: 'ฝ่ายภูมิสถาปัตย์',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-20',
    created_at: '2024-01-21T09:15:00Z',
  },
  {
    id: 'unassign_08',
    receive_no: 'RCV-67-019',
    title: 'ซื้อวัตถุดิบประกอบอาหารแห้งประจำเดือน',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'แผนกอาหารและเครื่องดื่ม',
      department: {
        name: 'แผนกอาหารและเครื่องดื่ม',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-02-25',
    created_at: '2024-01-21T10:00:00Z',
  },
  {
    id: 'unassign_09',
    receive_no: 'RCV-67-020',
    title: 'จ้างผู้ตรวจประเมินคุณภาพ ISO 9001',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'งานประกันคุณภาพ',
      department: {
        name: 'งานประกันคุณภาพ',
      },
    },
    procurement_type: 'LT500K',
    template_type: 'LT500K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-15',
    created_at: '2024-01-21T15:30:00Z',
  },
  {
    id: 'unassign_10',
    receive_no: 'RCV-67-021',
    title: 'จัดซื้อหูฟังสำหรับการสอบ Listening',
    status: 'UNASSIGNED',
    request_unit: {
      name: 'ศูนย์ภาษา',
      department: {
        name: 'ศูนย์ภาษา',
      },
    },
    procurement_type: 'LT100K',
    template_type: 'LT100K',
    urgent_status: 'NORMAL',
    expected_approval_date: '2024-03-08',
    created_at: '2024-01-22T08:00:00Z',
  },
];

export const MOCK_USER_SELECTION: UserSelectionResponse = {
  id: 'unit_procure_01',
  name: 'ฝ่ายพัสดุและจัดซื้อ',
  entity_type: 'unit',
  data: [
    {
      id: 'u-101',
      full_name: 'นายสมชาย ใจดี',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-102',
      full_name: 'นางสาวสมหญิง รักงาน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-103',
      full_name: 'นายวิชัย เก่งวิทย์',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-104',
      full_name: 'นางมาลี สีสวย',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-105',
      full_name: 'นายกล้าหาญ ชาญชัย',
      role: 'HEAD_OF_UNIT',
    },
    {
      id: 'u-106',
      full_name: 'นางสาวปิติ ยินดี',
      role: 'DOCUMENT_STAFF',
    },
    {
      id: 'u-107',
      full_name: 'นายมานะ อดทน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-108',
      full_name: 'นางสาวชูใจ ใฝ่เรียน',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-109',
      full_name: 'นายปัญญา รอบรู้',
      role: 'GENERAL_STAFF',
    },
    {
      id: 'u-110',
      full_name: 'นางแก้วตา ดวงใจ',
      role: 'GENERAL_STAFF',
    },
  ],
};

export const MOCK_USER: User = {
  id: 'user-01',
  username: 'user',
  name: 'user',
  email: 'user@gmail.com',
  role: 'GENERAL_STAFF',
  isStaff: true,
  department: {
    id: 'dept-01',
    name: 'procurement',
  },
  unit: {
    id: 'unit-01',
    name: 'procurement-1',
  },
  token: 'mock-token-123',
};

export const MOCK_USERS_BY_ROLE: Record<string, User> = {
  SUPER_ADMIN: {
    id: 'user-super-admin',
    username: 'superadmin',
    name: 'Super Admin User',
    email: 'superadmin@example.com',
    role: 'SUPER_ADMIN',
    isStaff: true,
    department: { id: 'dept-01', name: 'Administration' },
    unit: { id: 'unit-01', name: 'Executive Office' },
    token: 'mock-token-super-admin',
  },
  ADMIN: {
    id: 'user-admin',
    username: 'admin',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'ADMIN',
    isStaff: true,
    department: { id: 'dept-01', name: 'Administration' },
    unit: { id: 'unit-02', name: 'Admin Office' },
    token: 'mock-token-admin',
  },
  HEAD_OF_DEPARTMENT: {
    id: 'user-hod',
    username: 'hod',
    name: 'Head of Department',
    email: 'hod@example.com',
    role: 'HEAD_OF_DEPARTMENT',
    isStaff: false,
    department: { id: 'dept-02', name: 'Procurement Department' },
    token: 'mock-token-hod',
  },
  HEAD_OF_UNIT: {
    id: 'user-hou',
    username: 'hou',
    name: 'Head of Unit',
    email: 'hou@example.com',
    role: 'HEAD_OF_UNIT',
    isStaff: false,
    department: { id: 'dept-02', name: 'Procurement Department' },
    unit: { id: 'unit-03', name: 'Procurement Unit 1' },
    token: 'mock-token-hou',
  },
  REPRESENTATIVE: {
    id: 'user-rep',
    username: 'representative',
    name: 'Representative User',
    email: 'rep@example.com',
    role: 'REPRESENTATIVE',
    isStaff: false,
    department: { id: 'dept-03', name: 'Academic Department' },
    unit: { id: 'unit-04', name: 'Academic Unit 1' },
    token: 'mock-token-rep',
  },
  DOCUMENT_STAFF: {
    id: 'user-doc',
    username: 'docstaff',
    name: 'Document Staff',
    email: 'docstaff@example.com',
    role: 'DOCUMENT_STAFF',
    isStaff: true,
    department: { id: 'dept-01', name: 'Procurement Department' },
    unit: { id: 'unit-05', name: 'Document Processing' },
    token: 'mock-token-doc',
  },
  FINANCE_STAFF: {
    id: 'user-finance',
    username: 'financestaff',
    name: 'Finance Staff',
    email: 'finance@example.com',
    role: 'FINANCE_STAFF',
    isStaff: true,
    department: { id: 'dept-04', name: 'Finance Department' },
    unit: { id: 'unit-06', name: 'Finance Unit' },
    token: 'mock-token-finance',
  },
  GENERAL_STAFF: {
    id: 'user-general',
    username: 'generalstaff',
    name: 'General Staff',
    email: 'general@example.com',
    role: 'GENERAL_STAFF',
    isStaff: true,
    department: { id: 'dept-01', name: 'Procurement Department' },
    unit: { id: 'unit-07', name: 'General Services' },
    token: 'mock-token-general',
  },
  GUEST: {
    id: 'user-guest',
    username: 'guest',
    name: 'Guest User',
    email: 'guest@example.com',
    role: 'GUEST',
    isStaff: false,
    token: 'mock-token-guest',
  },
};

export const MOCK_USER_PROJECT_STATS = {
  data: [
    {
      id: 'u-101',
      full_name: 'นายสมชาย ใจดี',
      project_count: 12,
    },
    {
      id: 'u-102',
      full_name: 'นางสาวสมหญิง รักงาน',
      project_count: 8,
    },
    {
      id: 'u-103',
      full_name: 'นายวิชัย เก่งวิทย์',
      project_count: 15,
    },
    {
      id: 'u-104',
      full_name: 'นางมาลี สีสวย',
      project_count: 6,
    },
    {
      id: 'u-105',
      full_name: 'นายกล้าหาญ ชาญชัย',
      project_count: 10,
    },
    {
      id: 'u-106',
      full_name: 'นางสาวปิติ ยินดี',
      project_count: 4,
    },
    {
      id: 'u-107',
      full_name: 'นายมานะ อดทน',
      project_count: 9,
    },
    {
      id: 'u-108',
      full_name: 'นางสาวชูใจ ใฝ่เรียน',
      project_count: 7,
    },
    {
      id: 'u-109',
      full_name: 'นายปัญญา รอบรู้',
      project_count: 11,
    },
    {
      id: 'u-110',
      full_name: 'นางแก้วตา ดวงใจ',
      project_count: 5,
    },
    {
      id: 'u-111',
      full_name: 'นายธนา มั่นคง',
      project_count: 13,
    },
    {
      id: 'u-112',
      full_name: 'นางสาวสุดา เพียร',
      project_count: 8,
    },
    {
      id: 'u-113',
      full_name: 'นายประสิทธิ์ ขยัน',
      project_count: 14,
    },
    {
      id: 'u-114',
      full_name: 'นางจิตรา สุขใจ',
      project_count: 6,
    },
    {
      id: 'u-115',
      full_name: 'นายอนุชา รุ่งเรือง',
      project_count: 10,
    },
  ],
};

export const MOCK_PROJECT_DETAIL: ProjectDetail = {
  id: 'proj-12345-abcd',
  procurement_type: 'MT500K',
  current_template_type: 'MT500K',
  is_urgent: true,
  title: 'โครงการจัดซื้อครุภัณฑ์คอมพิวเตอร์และอุปกรณ์ต่อพ่วง ประจำปี 2569',
  description:
    'จัดซื้อเครื่องคอมพิวเตอร์ All-in-One จำนวน 10 เครื่อง สำหรับห้องปฏิบัติการคอมพิวเตอร์',
  budget: 480000,
  status: 'IN_PROGRESS',
  receive_no: '69/0012',
  less_no: 'LP-2569-0045',
  pr_no: null,
  po_no: null,
  contract_no: null,
  migo_no: null,
  expected_approval_date: '2026-02-28T00:00:00.000Z',
  created_at: '2026-01-20T09:00:00.000Z',
  updated_at: '2026-01-25T14:30:00.000Z',

  vendor: {
    name: 'บริษัท ไอที โซลูชั่น จำกัด',
    tax_id: '1234567890123',
    email: 'sales@itsolution.co.th',
  },

  requester: {
    unit_name: 'ภาควิชาวิทยาการคอมพิวเตอร์',
    unit_id: 'unit-cs-01',
    dept_name: 'คณะวิทยาศาสตร์',
    dept_id: 'dept-sci-01',
  },

  creator: {
    full_name: 'นางสาวสมหญิง รักงาน',
    role: 'GENERAL_STAFF',
    unit_name: 'งานพัสดุ',
    unit_id: 'unit-procure-01',
    dept_name: 'สำนักงานเลขานุการ',
    dept_id: 'dept-office-01',
  },

  assignee_procurement: {
    id: 'staff-001',
    full_name: 'นายสมชาย ใจดี',
    role: 'GENERAL_STAFF',
    unit_name: 'งานพัสดุ',
    unit_id: 'unit-procure-01',
  },

  assignee_contract: {
    id: 'staff-002',
    full_name: 'นางหัวหน้า งานดี',
    role: 'HEAD_OF_UNIT',
    unit_name: 'งานสัญญา',
    unit_id: 'unit-contract-01',
  },

  // Currently stuck at Step 2
  current_step: {
    name: 'จัดทำรายงานขอซื้อหรือขอจ้าง, คำสั่งแต่งตั้งคณะกรรมการซื้อหรือจ้าง และหนังสือเชิญชวน',
    order: 2,
  },

  // Full Workflow Definition (MT500K)
  workflow: {
    type: 'MT500K',
    steps: [
      {
        name: 'จัดทำแผนจัดการจัดซื้อจัดจ้าง และจัดทำคำสั่งแต่งตั้งคณะกรรมการฯ TOR',
        order: 1,
        required_step: [],
        required_documents: [
          {
            type: 'FILE_UPLOAD',
            label: 'แผนการจัดซื้อจัดจ้าง',
            field_key: 'mt500k_procurement_plan_file',
            is_required: false,
          },
          {
            type: 'FILE_UPLOAD',
            label: 'คำสั่งแต่งตั้งคณะกรรมการจัดทำขอบเขตของงาน (TOR)',
            field_key: 'mt500k_tor_committee_appt_file',
            is_required: true,
          },
        ],
      },
      {
        name: 'จัดทำรายงานขอซื้อหรือขอจ้าง, คำสั่งแต่งตั้งคณะกรรมการซื้อหรือจ้าง และหนังสือเชิญชวน',
        order: 2,
        required_step: [1],
        required_documents: [
          {
            type: 'FILE_UPLOAD',
            label: 'รายงานขอซื้อ/จ้าง',
            field_key: 'mt500k_requisition_report_file',
            is_required: true,
          },
          {
            type: 'FILE_UPLOAD',
            label: 'คำสั่งแต่งตั้งคณะกรรมการซื้อ/จ้าง',
            field_key: 'mt500k_procurement_committee_file',
            is_required: true,
          },
          {
            type: 'FILE_UPLOAD',
            label: 'หนังสือเชิญชวน',
            field_key: 'mt500k_invitation_letter_file',
            is_required: false,
          },
        ],
      },
      {
        name: 'จัดทำรายงานผลการพิจารณาจัดซื้อจัดจ้าง, รายงานผลฯ อนุมัติ ประกาศผู้ชนะ และหนังสือสนองรับราคาฯ',
        order: 3,
        required_step: [2],
        required_documents: [
          {
            type: 'FILE_UPLOAD',
            label: 'รายงานผลการพิจารณาและอนุมัติสั่งซื้อ/จ้าง',
            field_key: 'mt500k_consideration_report_file',
            is_required: true,
          },
          {
            type: 'FILE_UPLOAD',
            label: 'ประกาศผู้ชนะการเสนอราคา',
            field_key: 'mt500k_winner_announcement_file',
            is_required: true,
          },
          {
            type: 'TEXT_INPUT',
            label: 'เลขที่ใบขอซื้อ (PR Number)',
            field_key: 'mt500k_pr_number',
            is_required: true,
          },
        ],
      },
      {
        name: 'จัดทำร่างสัญญา / ใบสั่งซื้อสั่งจ้าง / หนังสือข้อตกลง',
        order: 4,
        required_step: [3],
        required_documents: [
          {
            type: 'FILE_UPLOAD',
            label: 'สัญญา / ใบสั่งซื้อสั่งจ้าง / หนังสือข้อตกลง',
            field_key: 'mt500k_contract_doc_file',
            is_required: true,
          },
          {
            type: 'TEXT_INPUT',
            label: 'เลขที่ใบสั่งซื้อ (PO Number)',
            field_key: 'mt500k_po_number',
            is_required: true,
          },
        ],
      },
      {
        name: 'test for every input type',
        order: 5,
        required_step: [],
        required_documents: [
          {
            type: 'FILE_UPLOAD',
            label: 'เอกสารแนบ (File Upload)',
            field_key: 'mt500k_test_file_upload',
            is_required: false,
          },
          {
            type: 'TEXT_INPUT',
            label: 'ข้อความสั้น (Text Input)',
            field_key: 'mt500k_test_text_input',
            is_required: false,
          },
          {
            type: 'DATE_PICKER',
            label: 'วันที่ (Date Picker)',
            field_key: 'mt500k_test_date_picker',
            is_required: false,
          },
          {
            type: 'DATE_WITH_CHECKBOX',
            label: 'วันที่พร้อมช่องทำเครื่องหมาย (Date with Checkbox)',
            field_key: 'mt500k_test_date_with_checkbox',
            is_required: false,
          },
          {
            type: 'BOOLEAN',
            label: 'ใช่/ไม่ใช่ (Boolean)',
            field_key: 'mt500k_test_boolean',
            is_required: false,
          },
        ],
      },
    ],
  },

  submissions: [
    {
      step_name: 'จัดทำแผนจัดการจัดซื้อจัดจ้าง และจัดทำคำสั่งแต่งตั้งคณะกรรมการฯ TOR',
      step_order: 1,
      submission_round: 1,
      status: 'APPROVED',
      submitted_by: 'นายสมชาย ใจดี',
      submitted_at: '2026-01-21T10:00:00.000Z',
      action_by: 'นางหัวหน้า งานดี',
      action_at: '2026-01-21T14:00:00.000Z',
      documents: [
        {
          field_key: 'mt500k_procurement_plan_file',
          file_name: 'แผนจัดซื้อ_2569.pdf',
          file_path: '/uploads/proj-123/plan.pdf',
        },
        {
          field_key: 'mt500k_tor_committee_appt_file',
          file_name: 'คำสั่งแต่งตั้ง_TOR.pdf',
          file_path: '/uploads/proj-123/tor_appt.pdf',
        },
      ],
      meta_data: {},
      comments: 'เอกสารครบถ้วน ดำเนินการต่อได้',
    },

    // --- Step 2 History: Round 1 (Returned) ---
    {
      step_name:
        'จัดทำรายงานขอซื้อหรือขอจ้าง, คำสั่งแต่งตั้งคณะกรรมการซื้อหรือจ้าง และหนังสือเชิญชวน',
      step_order: 2,
      submission_round: 1,
      status: 'REJECTED',
      submitted_by: 'นายสมชาย ใจดี',
      submitted_at: '2026-01-23T09:30:00.000Z',
      action_by: 'นางหัวหน้า งานดี',
      action_at: '2026-01-23T11:15:00.000Z',
      documents: [
        {
          field_key: 'mt500k_requisition_report_file',
          file_name: 'รายงานขอซื้อ.pdf',
          file_path: '/uploads/proj-123/req_v1.pdf',
        },
      ],
      meta_data: {},
      comments:
        'ช่วยแก้ไขรายชื่อกรรมการคนที่ 2 เนื่องจากพิมพ์นามสกุลผิด และแนบไฟล์คำสั่งแต่งตั้งเพิ่มด้วยครับ',
    },

    // --- Step 2 History: Round 2 (Submitted - Current Active State) ---
    {
      step_name:
        'จัดทำรายงานขอซื้อหรือขอจ้าง, คำสั่งแต่งตั้งคณะกรรมการซื้อหรือจ้าง และหนังสือเชิญชวน',
      step_order: 2,
      submission_round: 2,
      status: 'ACCEPTED',
      submitted_by: 'นายสมชาย ใจดี',
      submitted_at: '2026-01-24T15:45:00.000Z',
      // No action yet because it's pending review
      action_by: null,
      action_at: null,
      documents: [
        {
          field_key: 'mt500k_requisition_report_file',
          file_name: 'รายงานขอซื้อ_แก้ไข.pdf',
          file_path: '/uploads/proj-123/req_v2.pdf',
        },
        {
          field_key: 'mt500k_procurement_committee_file',
          file_name: 'คำสั่งแต่งตั้ง_กรรมการ.pdf',
          file_path: '/uploads/proj-123/committee.pdf',
        },
      ],
      meta_data: {},
    },
  ],
};

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'dept-01',
    name: 'คณะวิทยาศาสตร์',
    code: '1001',
  },
  {
    id: 'dept-02',
    name: 'คณะวิศวกรรมศาสตร์',
    code: '1002',
  },
  {
    id: 'dept-03',
    name: 'สำนักวิทยบริการ',
    code: '2001',
  },
  {
    id: 'dept-04',
    name: 'กองบริหารงานบุคคล',
    code: '3001',
  },
  {
    id: 'dept-05',
    name: 'กองอาคารสถานที่',
    code: '3002',
  },
];
